### ISSUE TITLE
Support JSON format output

### ISSUE THREAD

**Issue by yu-iskw** [quarylabs/sqruff#1011]
### What would you like to see?

It would be great to support JSON format output as sqlfluff provides. We can enhance the JSON-formatted output with custom tools. It seems that sqlruff 0.21.7 doesn't support the JSON format output.

```
$ sqlfluff lint --help
...
  -f, --format [human|json|yaml|github-annotation|github-annotation-native|none]
                                  What format to return the lint result in
                                  (default=human).
```

### Checked issues

- [x] I have checked this request in the [issues](https://github.com/quarylabs/sqruff/issues).

**Comment by benfdking** [comment]
Thanks for the request! That should be done, and it's in the latest release. Feel free to let me know if you have any thoughts/suggestions; it's based on LSP diagnostics standards. 

https://github.com/quarylabs/sqruff/pulls?q=is%3Apr+is%3Aclosed#:~:text=feat%3A%20implement%20json%20type%20returner
