### ISSUE TITLE
Brew - download link is broken

### ISSUE THREAD

**Issue by haithem-souala** [quarylabs/sqruff#189]
Hi,

The download URL is not correct:

```
haithem@dbt-ultimile % brew install quarylabs/quary/sqruff
==> Fetching quarylabs/quary/sqruff
==> Downloading https://github.com/quarylabs/quary/releases/download/0.0.6/sqruff-darwin-aarch64.tar.gz
curl: (22) The requested URL returned error: 404
```

**Comment by benfdking** [comment]
Hey @haithem-souala 

Sorry, you've had that experience. Thank you though for filing the issue. We don't quite understand how that has happened but we're pushing a fix:

https://github.com/quarylabs/homebrew-quary/pull/7

We'll also investigate it to prevent it happening again. I'll let you know when it's been merged.

**Comment by benfdking** [comment]
https://github.com/quarylabs/homebrew-quary/pull/7 was merged ;) 

Let me know if that works for you.

**Comment by benfdking** [comment]
Hey @haithem-souala,

It looks like you are trying to run `sqruff` on top of a dbt project. We don't yet support parsing the dbt syntax, in fact we only support ANSI. My guess is that is why the parser is breaking.

**Comment by haithem-souala** [comment]
Understood, thank you!

**Comment by benfdking** [comment]
I would definitely recommend https://sqlfluff.com/ in the meantime.
