### ISSUE TITLE
Add descriptions to the rules in a callback method so we can generate the description page of them eventually 

### ISSUE THREAD

**Issue by benfdking** [quarylabs/sqruff#215]
It would be useful for the rules to also have the function 

```
trait Rule {
  fn get_description() -> &str 
}
```

That contains the comment the Python code contains so we can use it to generate docs in the future.

**Comment by gvozdvmozgu** [comment]
We already have a method `fn description(&self) -> &'static str`.

**Comment by benfdking** [comment]
Nice, I guess we just need to remove the default and start implementing it. Thanks for pointing that out!
