### ISSUE TITLE
[FEATURE]: Implement Config File

### ISSUE THREAD

**Issue by louisjoecodes** [quarylabs/sqruff#297]
The `sqruff` cli should read a file called `.sqruff` from the root of the directory on each command.

Example structure:

```yaml
[sqruff]
# Supported dialects https://github.com/quarylabs/sqruff
# Or run 'sqruff dialects'
dialect = ansi

# Comma separated list of rules to exclude, or None
# AM04 (ambiguous.column_count) and ST06 (structure.column_order) are
# two of the more controversial rules included to illustrate usage.
exclude_rules = ambiguous.column_count, structure.column_order

# The default configuration for capitalisation rules is "consistent"
# which will auto-detect the setting from the rest of the file. This
# is less desirable in a new project and you may find this (slightly
# more strict) setting more useful.
# Typically we find users rely on syntax highlighting rather than
# capitalisation to distinguish between keywords and identifiers.
# Clearly, if your organisation has already settled on uppercase
# formatting for any of these syntax elements then set them to "upper".
# See https://stackoverflow.com/questions/608196/why-should-i-capitalize-my-sql-keywords-is-there-a-good-reason
[sqruff:rules:capitalisation.keywords]
capitalisation_policy = lower
[sqruff:rules:capitalisation.identifiers]
extended_capitalisation_policy = lower
[sqruff:rules:capitalisation.functions]
extended_capitalisation_policy = lower
[sqruff:rules:capitalisation.literals]
capitalisation_policy = lower
[sqruff:rules:capitalisation.types]
extended_capitalisation_policy = lower

```

Success criteria:
- As a user can I run `sqruff lint` without specifying a dialect?
- As a user can I exclude rules to check?
- As a user can I define a max file-length?
- As a user can I define rule-specific policies i.e. set the capitalisation policy.

**Comment by louisjoecodes** [comment]
@benfdking & @gvozdvmozgu  to review

**Comment by benfdking** [comment]
A few of my thoughts/opinions that are running through my mind

I would start by not deviating from anything that `sqlfluff` does, as, in the first instance, our V1 should still try to be as close as possible in terms of fidelity. Even if that is sub-ideal initially, I think we can change that down the line when we are more confident in it. That doesn't extend to all the naming conventions; I just think we pick the latest and maybe not try to backfill everyone. 

For V2,

After having achieved some parity, structurally, I think it's important that the rule options are defined strictly in code. Letting each rule define its parameters, as well as any rule cross dependencies and what it can take, will make the project much easier to debug and scale. For example, at the moment, we have a default config that is a [toml] file. I think we should be able to generate a file from each rule that gives it its "default."
Over time, equally, I think we should try to move away as much as possible from maps into strict types that make the project feel more robust.
Once those things are in place, I think it will be easier to move defaults and then try to part ways with `sqruff`.

**Comment by gvozdvmozgu** [comment]
It seems this is already implemented? At least version 1, as described above

**Comment by benfdking** [comment]
👍 

Happy to close. @louisjoecodes ?

**Comment by louisjoecodes** [comment]
Hey @gvozdvmozgu, are there any questions f
