### ISSUE TITLE
[Dialect] Implement PostgreSQL Dialect support

### ISSUE THREAD

**Issue by louisjoecodes** [quarylabs/sqruff#328]
Adding support for the PostgreSQL dialect.

**Comment by louisjoecodes** [comment]
Hey @gvozdvmozgu I think the next logical dialect to support in sqruff is Postgres.

**Comment by benfdking** [comment]
@gvozdvmozgu anything left to do for this one?

**Comment by gvozdvmozgu** [comment]
we can close the issue.
