### ISSUE TITLE
Split `sqruff-lib` into separate crates

### ISSUE THREAD

**Issue by gvozdvmozgu** [quarylabs/sqruff#483]
Breaking up the code into more crates helps Rust apply incremental compilation and parallelization more effectively, improving compile time.

**Comment by benfdking** [comment]
https://github.com/quarylabs/sqruff/pull/727 will separate it into:

1. Core (Lexer/Parser and interfaces)
2. Dialects (Dialect implementations)
3. Sqruff (Rules and linting infrastructure)

In theory, we should then be able to
1. move the `lineage` and `sqlinference` to only use core and dialects
2. implement each dialect as a feature to reduce compile sizes

I am also slightly intrigued about which parts of the codebase we could make more "boring". There's lots that we have added for performance sake but are there ways of packaging something "more boring" and that maybe for WASM target for example is lighter weight.

**Comment by benfdking** [comment]
Things left to do: 

- [ ] Move the lineage and sqlinference to core and dialects
- [ ] Add features for all the dialects
- [ ]

**Comment by benfdking** [comment]
I think we've start this, happy to close this unless you have proper plans for the next thing? @gvozdvmozgu

**Comment by gvozdvmozgu** [comment]
I think we can close this now.
