### ISSUE TITLE
Tell user why a file wasn't processed

### ISSUE THREAD

**Issue by colindean** [quarylabs/sqruff#590]
When I run sqruff against a single file, it's not processed and I'm not told why.

```
$ sqruff lint src/main/resources/scripts/model_metrics.hql 
The linter processed 0 file(s).
All Finished 📜 🎉
```

When I run it in a directory where I've got 2 SQL files, it doesn't tell me why it's skipping.

```
$ sqruff lint .
The linter processed 0 file(s).
All Finished 📜 🎉
```

I speculate that it's only looking for files ending with `.sql`. That might not always be true: convention among our org of hundreds using Hive and Spark is to use `.hql`.

**Comment by benfdking** [comment]
It is, indeed. Thanks for reporting this! We'll try to fix this ASAP.

**Comment by benfdking** [comment]
This is somewhat fixed, see this for how it works https://github.com/quarylabs/sqruff/pull/594

Just doing a push at the moment. And we'll need to see the specific file fix.

**Comment by benfdking** [comment]
That's also now pushed and downloadable with brew.

**Comment by benfdking** [comment]
I am going to close this as in our latest version, we fix this in 2 ways: 
1. We allow the config override
2. If you specify a file directly we ignore the config and just lint/fix it.
