### ISSUE TITLE
Support for Athena and Trino dialect

### ISSUE THREAD

**Issue by nicor88** [quarylabs/sqruff#591]
Athena is Trino's managed solution in the AWS ecosystem. Trino (and therefore Athena) support ANSI dialect but there are some syntax variations.
Considering athena and trino are widely adopted, it will be nice to support them fully, and allow people to replace the widely used sqlfluff with sqruff.

**Comment by benfdking** [comment]
Totally agree! Thanks for flagging.

**Comment by KulykDmytro** [comment]
need this too

**Comment by benfdking** [comment]
A start https://github.com/quarylabs/sqruff/pull/690

**Comment by benfdking** [comment]
And for athena https://github.com/quarylabs/sqruff/pull/696

**Comment by benfdking** [comment]
Athena is done and being deployed right now.

**Comment by benfdking** [comment]
There's also Trino coming through right now.

**Comment by benfdking** [comment]
I am marking this as done, as the new version has been pushed everywhere. Please let us know if you have any problems with it!
