### ISSUE TITLE
Add ability to specify config file path 

### ISSUE THREAD

**Issue by ashish10alex** [quarylabs/sqruff#636]
Hi, 
Is it possible to get the equivalent of 

```
sqruff fix --config="./path/to/my/.sqlfluff"
```

This functionality currently exists in sqlfluff and can be very handy if your config dot files are in a separate directory. 
From what I have tried the default functionality seems to be that it picks a config file it it is available in the root directory of where the cli is called from

**Comment by benfdking** [comment]
This was merged, just doing a build.

**Comment by quassy** [comment]
I guess all builds were finished and this was released in 0.14.0, yet when I brew install I only get 0.13.0? Is that long delay between build/release and brew availability expected?

**Comment by benfdking** [comment]
Sorry yep pipeline isn't fixed. Will push to brew.
