### ISSUE TITLE
Support for placeholder templater

### ISSUE THREAD

**Issue by ashish10alex** [quarylabs/sqruff#642]
Hi, 
Would it be possible to add support for [custom palceholder templaters](https://docs.sqlfluff.com/en/3.1.1/configuration/templating/placeholder.html)  similar to how sqlfluff does

```
[sqlfluff:templater:placeholder]
param_regex = __(?P<param_name>[\w_]+)__
my_name = 'john'
```

**Comment by benfdking** [comment]
Hey @ashish10alex,

Just pushed a pr with this implementation for you, so hopefully with you soon.

**Comment by benfdking** [comment]
There's still a little more work than expected but the templater is defined.

**Comment by gvozdvmozgu** [comment]
Can we close this?

**Comment by benfdking** [comment]
I think let's just push a build before declaring it done.

**Comment by benfdking** [comment]
Pushed to brew so will close. @ashish10alex  let us know if you need anything else.
