### ISSUE TITLE
Placeholder templater not working as expected

### ISSUE THREAD

**Issue by ashish10alex** [quarylabs/sqruff#670]
The placeholder template introduced in https://github.com/quarylabs/sqruff/issues/642 is not working as expected as it seems to replaces the block where the regex matches with the replacement string 

Sqlfluff config file 

```
[sqlfluff]
templater = placeholder
dialect = bigquery


[sqlfluff:rules:capitalisation.keywords]
# Keywords must be capitalised
capitalisation_policy = upper

[sqlfluff:rules:capitalisation.identifiers]
# Unquoted identifiers
extended_capitalisation_policy=upper
unquoted_identifiers_policy=all


# 1 is used by sqlfluff to replace the regex match with the value of the placeholder
# if you have multiple placeholders, you can add more lines with the same format
# e.g. 2 = `gcp_project_id.my_dataset.my_table`
[sqlfluff:templater:placeholder]
param_regex = (?s)\$\{\s*self\s*\(\s*\)\s*\}|\$\{\s*ref\s*\(\s*(\"?\w+\"?|\{[^}]+\})\s*\)\s*\}|\$\{\s*ref\s*\(\s*\'\s*\d*\s*([\w]+)\s*\'\s*\)\s*\}|\$\{\s*[^}]*\s*\}
1 = my_table_or_replacement
2 = my_table_or_replacement
```

SQL file to try the fix on 

```sql
SELECT
    apple,
    berry
FROM ${ref("SHUTDOWN_DATES_ALL_PLANTS")}
```

Expected output when running `sqlfluff fix test.sql`

```
SELECT
    APPLE,
    BERRY
FROM ${ref("SHUTDOWN_DATES_ALL_PLANTS")}
```

Output when running `sqruff fix test.sql` 

```
SELECT
    APPLE,
    BERRY
FROM MY_TABLE_OR_REPLACEMENT
```

**Comment by gvozdvmozgu** [comment]
Good catch. It looks like some rules need to be updated so that they understand the templates.

**Comment by benfdking** [comment]
https://github.com/quarylabs/sqruff/pull/671

**Comment by gvozdvmozgu** [comment]
I looked into the issue in more detail, and we need to add support for the `ignore_templated_areas` option.

original code:
```python
if config.get("ignore_templated_areas", default=True):
    initial_linting_errors = cls.remove_templated_errors(initial_linting_errors)
```

in some rules they are disabled manually, but in general they seem to be simply removed if the ignore option is enabled

**Comment by benfdking** [comment]
@ashish10alex just tested that and it looks much better!

**Comment by benfdking** [comment]
@ashish10alex it should be done but do let me know if you find anything else.
