### ISSUE TITLE
Unable to use `--config` to specify config file path

### ISSUE THREAD

**Issue by ashish10alex** [quarylabs/sqruff#708]
Hi, 
I am unable to specify the config file path to fix sql file. The ability to specify config file path was introduced in https://github.com/quarylabs/sqruff/issues/636 

version of sqruff: `sqruff 0.15.7`

Please see my below attempts to specify the config file 

![CleanShot 2024-09-09 at 20 11 16@2x](https://github.com/user-attachments/assets/761c44a5-677e-4692-aaa9-6dc9a6bf7766)

**What works ?** -  If the config file is in the root directory where I am running it from it successfully formats the file 

Please feel free to correct me if I have made a silly mistake

**Comment by benfdking** [comment]
Sorry about that, that was addressed.
