### ISSUE TITLE
Python support/installation with python

### ISSUE THREAD

**Issue by concur1** [quarylabs/sqruff#739]
First of all Sqruff is a very cool project so thank you!

I would like Sqruff to be made available as a python package so that I am able to install Sqruff using a python package manager such as PIP, Poetry  or UV. 

Python support would make using Sqruff easier for many python based projects as:
1. Some Python based teams will only have access to python packages and no ability to install packages to the OS.
2. Having the Sqruff version be defined in a pyproject.toml file makes it much easier to set up the environment of a project. Currently manual steps would be required.

Similar Rust based project such as Ruff and Polars are made available as a python package and I think this really helps their reach.

**Comment by benfdking** [comment]
Hey @concur1, thanks for all the fantastic feedback! We'll get to it 🚀

**Comment by concur1** [comment]
No problem!

I am happy to try and pitch in and help a bit with some of the things I suggested. So if you are happy with some of these suggestions and mark them ass accepted  I can will make a PR.

**Comment by benfdking** [comment]
Feel free to open PRs for the suggestions and we'll review.

**Comment by benfdking** [comment]
This is being deployed now with version 0.18.0 so we will have to see if it works.

**Comment by benfdking** [comment]
@concur1 pipeline has run so if you want to try it, let us know.

**Comment by concur1** [comment]
> @concur1 pipeline has run so if you want to try it, let us know.

Thanks, Yep, I have tested it on Ubuntu and it works fine.

**Comment by gvozdvmozgu** [comment]
Need to remember to document that this installation method exists.
