### ISSUE TITLE
Add issue template

### ISSUE THREAD

**Issue by concur1** [quarylabs/sqruff#741]
There is currently no issue template. Having an issue template could mean:
- More detailed bug reports
- More structured bug reports
- More searchable/discoverable issues

You could use a similar template to what the Ruff project uses: https://github.com/astral-sh/ruff/blob/05b406080ada9af8e5e0ff7c25b954fb4f3ae469/.github/ISSUE_TEMPLATE.md?plain=1

**Comment by benfdking** [comment]
Done! Thanks for the suggestion.
