### ISSUE TITLE
Github action to run sqruff

### ISSUE THREAD

**Issue by concur1** [quarylabs/sqruff#743]
It would be nice to have a github action to run Sqruff:

Here is the example action that Ruff has: https://github.com/ChartBoost/ruff-action

**Comment by benfdking** [comment]
We already do this with https://github.com/quarylabs/install-sqruff-cli-action to a large extent.

**Comment by benfdking** [comment]
https://github.com/quarylabs/sqruff/pull/744 documents the installation, so will mark this as done.

**Comment by concur1** [comment]
ahh nice, must have missed this when I looked earlier
