### ISSUE TITLE
Add config file examples

### ISSUE THREAD

**Issue by wood-jp** [quarylabs/sqruff#813]
Could you please add examples of how to disable specific rules or rule sets in the config file? I played around a bit, but had no success in guessing how to actually turn off any of the layout rules, or generally how to actually set anything other than the dialect.

**Comment by benfdking** [comment]
Hey @wood-jp,

Good shout. I'm sorry we haven't had more documentation about it before. It's probably because you can take it from `sqlfluff` but that does need to change, so I will add some stuff around this.

**Comment by benfdking** [comment]
https://github.com/quarylabs/sqruff/pull/816 here's a little start, but by no means is It the whole story. 

As you can see in this discussion https://github.com/quarylabs/sqruff/issues/798 config is something we think there is a little of work to do on.

**Comment by wood-jp** [comment]
Thanks @benfdking

**Comment by benfdking** [comment]
I am going to close this as we have started doing stuff here: https://github.com/quarylabs/sqruff/blob/main/docs/sample_configurations.md

please let me know if you need to reopen.
