### ISSUE TITLE
[Rule] LT01 - spacing

### ISSUE THREAD

**Issue by jordandakota** [quarylabs/sqruff#830]
L:   4 | P:  20 | LT01 | Expected single whitespace between "{" and "{".
                       | [layout.spacing]

In sqlfluff, this works:

[sqruff:layout:type:placeholder]
spacing_within = any
spacing_before = any
spacing_after = any

and adding -- noqa: LT01 to a line allows inline ignoring, but neither approaches work with current version of sqruff.

**Comment by benfdking** [comment]
Thanks for the feedback, will look into it.

**Comment by benfdking** [comment]
Related to https://github.com/quarylabs/sqruff/pull/855, this should add the `noqa` functionality

```sql
SELECT   1; --noqa: disable=LT01
```

**Comment by jordandakota** [comment]
Will the added noqa allow me to do something like:

```
with

generaljournal as (
select * from {{ source ("schema", "table") }}
-- noqa: disable=all
{% if is_incremental () %}
    {% call statement ('max_id', fetch_result = True) %}
    SELECT max(ID) as max_id FROM {{ this }}
    {% endcall %}
    {% set max_id = load_result('max_id')['data'][0][0] %}
    where ID > {{ max_id }}
{% endif %}
-- noqa: enable=all
)
```

We're getting an issue where having any of the {% jinja style operators in the beginning of the file causes downstream lints to end up looking like:

```
FROM GENERALJOURNAL GJ
JOIN businessentity BE
ON GJ.IDBEOWNER = BE.ID
JOIN GENERALJOURNALLINE GJL
ON GJ.ID = GJL.IDGENERALJOURNAL
JOIN GENERALLEDGERTRANSACTION GLT
ON GLT.IDGENERALJOURNALLINE = GJL.ID
```

**Comment by benfdking** [comment]
This won't be able to do a range just yet, but let me look into it. Now that we have the infrastructure, it should be much easier.

**Comment by jordandakota** [comment]
> This won't be able to do a range just yet, but let me look into it. Now that we have the infrastructure, it should be much easier.
> 
> Really, what this needs is a DBT templater... and I am at Coalesce, so I might feel inspired.

Sounds good Ben. I agree, a templater would work, but I can say that with this fix here it already has about 95% coverage on my project that uses dbt. It's just the incremental models that always have the jinja at the start where it fuzzes up and left align/capitalizes everything regardless of my settings.

**Comment by benfdking** [comment]
Latest version should have this in it. Just pushing to our brew.

**Comment by benfdking** [comment]
I am going to close this, but please reopen if you don't think it's fully addressed.
