### ISSUE TITLE
Can't parse DuckDB `create macro` statement

### ISSUE THREAD

**Issue by riziles** [quarylabs/sqruff#892]
Great utility here. Thank you for this wonderful package.

Just an FYI, the parser doesn't seem to be able to handle DuckDB's `create macro` syntax. For example:

```sql
create macro add_something(x) as (
  with cte as (
    select
      max(some_field) as some_value
    from
      some_table
  )
  select
    x + some_value
  from
    cte
);
```

Tagging @gvozdvmozgu because I believe he wrote the PR for the Duck DB dialect.

I'm slammed right now but hoping that at a later date I might be able to take a swing at a PR myself.

**Comment by benfdking** [comment]
Hi @riziles, although we haven't implemented macros in duckdb fully, the above statement now works.

**Comment by riziles** [comment]
@benfdking, this is fantastic! Thanks!
