### ISSUE TITLE
Ignore files with a .sqruffignore/.sqlfluffignore file

### ISSUE THREAD

**Issue by concur1** [quarylabs/sqruff#894]
Sorry if this already exists but I couldn't find anything in the readme and couldn't get it to work when testing.

It would be good if this feature of sqlfluff could be replicated: https://docs.sqlfluff.com/en/3.2.3/configuration/ignoring_configuration.html#sqlfluffignore

**Comment by benfdking** [comment]
This should be in the latest version, 0.20.0, and tested, so I will mark this as done. Thanks for the suggestion.

**Comment by concur1** [comment]
Nice, thank you, This is great news! 

Do you think you would be able to run the python release please?

**Comment by concur1** [comment]
ahhh, I see the python CI has failed for muslinux. I will take a look and see if I can fix later today.
