### ISSUE TITLE
Formatting sql text from stdin?

### ISSUE THREAD

**Issue by padhia** [quarylabs/sqruff#904]
I couldn't figure it out from the docs, so I apologize if this is already supported. I deal with SQL code generators that produce unformatted SQL. Is there a way to pipe the generated SQL to `sqruff` and have the formatted SQL output to stdout?

**Comment by benfdking** [comment]
There is no way to do that at the moment. It looks the standard approach is via a dash as following:

```
echo "def x(): return 1+1" | ruff check -
```

**Comment by benfdking** [comment]
I've just pushed a version with this in it. Let me know if that works for you.

**Comment by padhia** [comment]
Thank you very much for the quick turnaround!

**Comment by padhia** [comment]
The change works great! Thanks again.
