### ISSUE TITLE
Support aligning aliases

### ISSUE THREAD

**Issue by matthias-Q** [quarylabs/sqruff#983]
Hi, it would be nice if you could support aligning aliases
Before:
```sql
select
    aaaa as a,
    bbb as b,
    cc as c
from table

```

After:
```sql
select
    aaaa as a,
    bbb  as b,
    cc   as c
from table

```

At the moment this conflicts with rule LT01.

Thanks.

**Comment by gvozdvmozgu** [comment]
It seems to be working with this configuration, but I'm getting strange "TODO" diagnostics on the playground.
```
[sqlfluff:layout:type:alias_expression]
spacing_before = align
align_within = select_clause
align_scope = bracketed
```

**Comment by benfdking** [comment]
what are the TODOs @gvozdvmozgu, I don't see the?

**Comment by gvozdvmozgu** [comment]
![image](https://github.com/user-attachments/assets/97c8c25f-564c-4ff7-8c9b-d8cbbb472967)
I can't remember—was it just that we didn't write the diagnostic text, or was there something deeper?

**Comment by matthias-Q** [comment]
Ah thanks. That helps alot

**Comment by benfdking** [comment]
Documented and improved the output, @matthias-Q please reopen if you don't think we got your problem.
